@extends('layouts.app')

@section('title', 'Laporan Evaluasi Audit — ' . $report->title)
@section('subtitle', 'Laporan Resmi Kepatuhan Reklamasi KLHK')

@section('content')
<div class="max-w-4xl mx-auto space-y-8">

    <!-- Actions Header -->
    <div class="flex items-center justify-between">
        <a href="{{ route('reports.index') }}" class="text-xs font-semibold text-slate-400 hover:text-white flex items-center transition">
            &larr; Kembali ke Daftar Laporan
        </a>

        <div class="flex items-center space-x-3">
            <button onclick="window.print()" class="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 font-semibold text-xs rounded-xl transition">
                🖨️ Cetak / Print PDF
            </button>

            <!-- Status Form -->
            <form action="{{ route('reports.updateStatus', $report->id) }}" method="POST" class="flex items-center space-x-2">
                @csrf
                @method('PUT')
                <select name="status" onchange="this.form.submit()" class="px-3 py-1.5 bg-slate-900 border border-slate-700 text-xs rounded-xl font-bold text-emerald-400">
                    <option value="draft" {{ $report->status === 'draft' ? 'selected' : '' }}>Draft</option>
                    <option value="final" {{ $report->status === 'final' ? 'selected' : '' }}>Final Approved</option>
                    <option value="submitted" {{ $report->status === 'submitted' ? 'selected' : '' }}>Submitted KLHK</option>
                </select>
            </form>
        </div>
    </div>

    <!-- Official Report Document Paper Container -->
    <div class="bg-slate-900/90 border border-slate-800 rounded-3xl p-10 shadow-2xl space-y-8">
        <!-- Letterhead Header -->
        <div class="pb-6 border-b border-slate-800 flex items-start justify-between">
            <div>
                <span class="text-xs font-bold uppercase tracking-wider text-emerald-400">PT BUKIT ASAM TBK & PAMA PERSADA</span>
                <h1 class="text-2xl font-extrabold text-white mt-1">{{ $report->title }}</h1>
                <p class="text-xs text-slate-400 mt-1">Periode Evaluasi: {{ $report->period }} &bull; Tanggal Dibuat: {{ $report->generated_at ? $report->generated_at->format('d F Y H:i') : '-' }}</p>
            </div>
            <div class="text-right">
                <span class="px-3 py-1 text-xs font-bold rounded-lg bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 uppercase">
                    {{ $report->status }}
                </span>
            </div>
        </div>

        <!-- Site Executive Summary Table -->
        <div class="p-6 rounded-2xl bg-slate-950/80 border border-slate-800/80 space-y-4">
            <h4 class="text-xs font-bold uppercase tracking-wider text-slate-400">Executive Summary Metric Lapangan</h4>
            <div class="grid grid-cols-2 md:grid-cols-4 gap-4 text-xs">
                <div>
                    <span class="text-slate-500 block">Nama Blok</span>
                    <strong class="text-white text-sm">{{ $report->site->name ?? '-' }}</strong>
                </div>
                <div>
                    <span class="text-slate-500 block">Luas Area</span>
                    <strong class="text-white text-sm">{{ $report->site->area_hectares ?? 0 }} Ha</strong>
                </div>
                <div>
                    <span class="text-slate-500 block">Total Pohon Ditanam</span>
                    <strong class="text-blue-400 text-sm">{{ number_format($report->site->totalSeedlingsPlanted()) }} Pohon</strong>
                </div>
                <div>
                    <span class="text-slate-500 block">Rata Survival Rate</span>
                    <strong class="text-emerald-400 text-sm">{{ $report->site->averageSurvivalRate() }}%</strong>
                </div>
            </div>
        </div>

        <!-- AI Generated Audit Narrative Section -->
        <div class="space-y-4">
            <div class="flex items-center space-x-2">
                <div class="w-2 h-2 rounded-full bg-emerald-400"></div>
                <h3 class="text-sm font-bold text-white uppercase tracking-wider">Narasi Evaluasi Audit (Generated by Gemini AI Studio)</h3>
            </div>

            <div class="p-6 rounded-2xl bg-slate-950/60 border border-slate-800 text-slate-200 text-sm leading-relaxed whitespace-pre-line font-serif italic">
                {{ $report->ai_narrative }}
            </div>
        </div>

        <!-- Signatures Row -->
        <div class="pt-10 border-t border-slate-800 grid grid-cols-2 gap-8 text-center text-xs">
            <div>
                <p class="text-slate-400">Dibuat oleh:</p>
                <div class="h-16 flex items-center justify-center font-bold text-white text-sm">
                    {{ $report->generator->name ?? 'Evaluator Reklamasi' }}
                </div>
                <p class="text-slate-500">Divisi Lingkungan & K3L PT BA</p>
            </div>
            <div>
                <p class="text-slate-400">Disetujui oleh:</p>
                <div class="h-16 flex items-center justify-center font-bold text-emerald-400 text-sm">
                    Manager Reklamasi PAMA
                </div>
                <p class="text-slate-500">Penanggung Jawab Wilayah</p>
            </div>
        </div>
    </div>

</div>
@endsection
